version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: juliana20/gianyar_app
    env_file: .env
    container_name: app
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
  db: 
    image: mysql:8.0
    container_name: db
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db/:/var/lib/mysql
